export interface CommandParams {
    SRCLIB: string;
    SRCMBR: string;
    SRCTYPE: string;
    SRCFILE: string;
    OBJTYPE: string;
    CVTCLCSPEC: string;
    CVTDCLSPEC: string;
    EXPCSPECPY: string;
    FULLYFREE: string;
    MAXNOTFREE: string;
    FIRSTCOL: number;
    USEPARMNUM: string;
    TOSRCFILE: string;
    TOSRCMBR: string;
    REPLACE: string;
    CVT_CALL: string;
    CVT_GOTO: string;
    TAGFLDNAME: string;
    CVT_KLIST: string;
    CVT_MOVEA: string;
    INDENT: number;
    INDENTCMT: string;
    OPCODECASE: string;
    BLTFNCCASE: string;
    SPCWRDCASE: string;
    KEYWRDCASE: string;
    FLGCVTTYPE: string;
    CLRXREF: string;
    CLRFRMCHG: string;
    PRECPL: string;
    SRCDATE: string;
    CVT_SUBR: string;
    CHECKIND: string;
    SCANIND: string;
    LOOKUPIND: string;
    NUMTRUNCZ: string;
    NUMTRUNCA: string;
    NUMTRUNCB: string;
    NUMTRUNCM: string;
    NUMTRUNCD: string;
    EMPTYCMT: string;
    ALPHTONUM: string;
    KEEPDSIND: string;
}

export let commandParams: CommandParams = {
    SRCLIB: "",
    SRCMBR: "",
    SRCTYPE: "",
    OBJTYPE: "*NONE",
    SRCFILE: "",
    CVTCLCSPEC: "*FREE",
    CVTDCLSPEC: "*NO",
    EXPCSPECPY: "*NO",
    FULLYFREE: "*YES",
    MAXNOTFREE: "*NONE",
    FIRSTCOL: 1,
    USEPARMNUM: "*NO",
    TOSRCFILE: "*NONE",
    TOSRCMBR: "*FROMMBR",
    REPLACE: "*NO",
    CVT_CALL: "*YES",
    CVT_GOTO: "*ADVANCED",
    TAGFLDNAME: "ATag",
    CVT_KLIST: "*YES",
    CVT_MOVEA: "*BASE",
    INDENT: 0,
    INDENTCMT: "*YES",
    OPCODECASE: "*MIXED",
    BLTFNCCASE: "*MIXED",
    SPCWRDCASE: "*MIXED",
    KEYWRDCASE: "*MIXED",
    FLGCVTTYPE: "*NO",
    CLRXREF: "*YES",
    CLRFRMCHG: "*YES",
    PRECPL: "*ARCAD",
    SRCDATE: "*CURRENT",
    CVT_SUBR: "*NO",
    CHECKIND: "*WNG1",
    SCANIND: "*WNG1",
    LOOKUPIND: "*WNG1",
    NUMTRUNCZ: "*YES",
    NUMTRUNCA: "*YES",
    NUMTRUNCB: "*NO",
    NUMTRUNCM: "*YES",
    NUMTRUNCD: "*YES",
    EMPTYCMT: "*KEEP",
    ALPHTONUM: "*YES",
    KEEPDSIND: "*NO"
};