import { CommandParams } from "../models/command";

export const defaultConfig: CommandParams = {
    SRCLIB: "",
    SRCMBR: "",
    SRCTYPE: "",
    SRCFILE: "",
    CVTCLCSPEC: "*FREE",
    CVTDCLSPEC: "*YES",
    EXPCSPECPY: "*NO",
    FULLYFREE: "*YES",
    MAXNOTFREE: "*NONE",
    FIRSTCOL: 1,
    USEPARMNUM: "*NO",
    TOSRCFILE: "*NONE",
    TOSRCMBR: "*FROMMBR",
    TOSRCLIB: "",
    REPLACE: "*NO",
    CVT_CALL: "*YES",
    CVT_GOTO: "*ADVANCED",
    TAGFLDNAME: "ATag",
    CVT_KLIST: "*YES",
    CVT_MOVEA: "*ADVANCED",
    INDENT: 2,
    INDENTCMT: "*YES",
    OPCODECASE: "*MIXED",
    BLTFNCCASE: "*MIXED",
    SPCWRDCASE: "*MIXED",
    KEYWRDCASE: "*MIXED",
    FLGCVTTYPE: "*NO",
    CLRXREF: "*YES",
    CLRFRMCHG: "*YES",
    PRECPL: "*ARCAD",
    SRCDATE: "*CURRENT",
    CVT_SUBR: "*NO",
    CHECKIND: "*WNG1",
    SCANIND: "*WNG1",
    LOOKUPIND: "*WNG1",
    NUMTRUNCZ: "*YES",
    NUMTRUNCA: "*YES",
    NUMTRUNCB: "*NO",
    NUMTRUNCM: "*YES",
    NUMTRUNCD: "*YES",
    EMPTYCMT: "*KEEP",
    ALPHTONUM: "*YES",
    KEEPDSIND: "*NO"
};